### ISSUE TITLE
Terraform error on Windows

### ISSUE THREAD

**Issue by chrisgaun** [apprenda/hands-on-with-kubernetes-workshop#17]
digitalocean_ssh_key.default: Refreshing state... (ID: 7232704)
digitalocean_tag.cluster_tag: Creating...
  name: "" => "hands-on-kubernetes-workshop"
digitalocean_tag.cluster_tag: Creation complete
Error applying plan:

5 error(s) occurred:

* Resource 'digitalocean_tag.cluster_tag' does not have attribute 'id' for variable 'digitalocean_tag.cluster_tag.id'
* Resource 'digitalocean_tag.cluster_tag' does not have attribute 'id' for variable 'digitalocean_tag.cluster_tag.id'
* Resource 'digitalocean_tag.cluster_tag' does not have attribute 'id' for variable 'digitalocean_tag.cluster_tag.id'
* Resource 'digitalocean_tag.cluster_tag' does not have attribute 'id' for variable 'digitalocean_tag.cluster_tag.id'
* Resource 'digitalocean_tag.cluster_tag' does not have attribute 'id' for variable 'digitalocean_tag.cluster_tag.id'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by chrisgaun** [comment]
I fixed it on my laptop by changing the Cluster Tag in the Terraform but it didn't work for some of the people in the demo.

**Comment by swade1987** [comment]
Sounds to me like you may have already had `hands-on-kubernetes-workshop` as a cluster tag already on Digital Ocean?
