### ISSUE TITLE
Healthcheck demo - step missing

### ISSUE THREAD

**Issue by ojosdegris** [apprenda/hands-on-with-kubernetes-workshop#19]
When trying to run broken deployment I am getting error: 
      > kubectl create -f healthcheck/broken-deployment.yaml
      Error from server (AlreadyExists): error when creating "healthcheck/broken-deployment.yaml": deployments.extensions "probes-demo" already exists

Seems I need to delete healthy one first, then deploy broken one as last step of demo is delete broken  deployment.

**Comment by swade1987** [comment]
@ojosdegris please use ` kubectl apply -f healthcheck/broken-deployment.yaml`

**Comment by swade1987** [comment]
@ojosdegris is that doesn't fix it then please raise another issue.
