### ISSUE TITLE
Consider adding optional ssh key generation steps to make the tutorial more secure

### ISSUE THREAD

**Issue by yougotborked** [apprenda/hands-on-with-kubernetes-workshop#9]
Just so someone couldn't scrape this repo and mine digitalocean ip ranges for potential targets. 

During the presentation today I easily changed the keys to ones I generated, Additionally all I had to do was change the bootstrap node's stored key to that same key. Everything worked fine with those changes

I would probably recommend new key generation then re-use due to the nature of the tutorial classes  so no one's existing keys are compromised in the classroom.

**Comment by swade1987** [comment]
Makes sense, this repo was quickly created.

I might create a "make generate-keys" command and then use them.
